### ISSUE TITLE
connection problem 

### ISSUE THREAD

**Issue by jemory1602** [duju211/pin_strava#2]
Hi this looks really cool. I cloned this into R, and edited the client  STRAVA secret and KEY and app name in the file "define_strava_app"  to match my own.

 However, when I run targets::tar_make() in the counsel, and click on the link to get authorized on strava, I get this
{"message":"Bad Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}

**Comment by duju211** [comment]
Hi @jemory1602 ! Hmm strange.... 

Did you set STRAVA_KEY and STRAVA_SECRET (https://www.strava.com/settings/api) to the following two values:

![grafik](https://user-images.githubusercontent.com/13487201/155081220-bd2bc73d-5225-42e8-ba65-27ce50bffb30.png)

?
